### ISSUE TITLE
Incompatible with grunt 1.x

### ISSUE THREAD

**Issue by mar10** [DavidSouther/grunt-docco#44]
Please apply this PR: #43 and release a new version (patch 0.4.1 should be enough, I think).
Otherwise we get 
`npm ERR! peer dep missing: grunt@~0.4.0, required by grunt-docco@0.4.0`
when included in a project that requires grunt 1.x.

Thank you

**Comment by neocotic** [comment]
I've merged #43 in and released v0.5.0 which supports grunt v1.0. I've also deprecated all previous versions with a message stating that v0.5.0 is required for grunt v1.0 support.

**Comment by mar10** [comment]
Thank you!
